version: "3"

services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TAIGA_URL=
      - TAIGA_TOKEN=
      - REDIS_CONNSTRING=  # redis://host[:port]
#     - TIME_ZONE=
  redis:
    image: "redis:alpine"
